### ISSUE TITLE
Build of kernel fails for Wahoo

### ISSUE THREAD

**Issue by taichichuan** [sultanxda/android_kernel_google_wahoo#2]
Having just cloned the repo, I did the usual make wahoo_defconfig, and then did a make -j8 (I've got a Xeon).  However, the build crashes early with:

  HOSTCC  scripts/sortextable
make[2]: *** No rule to make target 'scripts/dtc-aosp/dtc/dtc.c', needed by 'scripts/dtc-aosp/dtc/dtc.o'.  Stop.
make[2]: *** Waiting for unfinished jobs....
  CC      scripts/mod/empty.o
scripts/Makefile.build:551: recipe for target 'scripts/dtc-aosp' failed
make[1]: *** [scripts/dtc-aosp] Error 2
make[1]: *** Waiting for unfinished jobs....

The dtc-aosp directory doesn't appear to have anything in it.  Is there a source for this code someplace or can I just modify the makefile to skip this step since it's not working?

TIA,

Mike

**Comment by kerneltoast** [comment]
git submodule init
git submodule update

**Comment by taichichuan** [comment]
OK, that did the trick.  Is there anyway to make that part of the normal documentation so that others know to do this?
