### ISSUE TITLE
Bright white flash when display turns off

### ISSUE THREAD

**Issue by TomK** [sultanxda/android_kernel_google_wahoo#4]
With the latest kernel (June Update)

When the screen turns off under any circumstance (with the power button, or waiting for the screen off duration), there is occasionally a bright white flash before the screen goes dark and then.

I believe this happens after the display has been on for a few minutes, or possibly after running specific types of app (games, perhaps?).

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-noclkpostpre_20200602.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4731183/Sultan-kernel-wahoo-noclkpostpre_20200602.zip)

Try this kernel.

**Comment by TomK** [comment]
Thank you, i'm just trying to get some definitive repro instructions so that i can confirm.  I couldn't get it to do it last night, but this morning it's now doing it again.  I'll get back to you asap!

**Comment by kerneltoast** [comment]
There's a good chance this has something to do with low temperatures. Maybe I should stick my phone in the fridge...

**Comment by TomK** [comment]
Sorry i didn't get around to this, I flashed the android 11 developer preview to see if they had changed the DFS to magically work on pixel devices here in UK, but sadly not (I wasn't holding out much hope for it tbh).

I'll be looking to re-flash the sultan kernel once i get back to android 10 stock, so will put this version and see how it goes.

**Comment by kerneltoast** [comment]
Some other users asked if I could get DFS to work in Europe. Maybe you can help test that after this is wrapped up.

**Comment by TomK** [comment]
i'm back on stock, sultan & magisk now.  I ran some tests last night and am monitoring it this morning (which is when I normally notice this issue).  I'll update the issue with anything I find.

I'm more than happy to assist with testing DFS 👍

**Comment by TomK** [comment]
@kerneltoast using the zip you supplied I'm still able to make it flash.
I've loaded a game (Darkfire Heroes) and tap around in the game for roughly 2 mins and then and allow the screen to turn off with the timeout OR the power button, it's flashing consistently.

If the screen is off for a few minutes the flashing will no longer occur until i go back to using the game again for a little while.

Surface temperature of the device is approx 25C / 77F when this issue occurs.

**Comment by TomK** [comment]
Battery has now dropped below 90% and i can't seem to get it to flash any more.

**Comment by TomK** [comment]
Downloaded a different game (RaceCraft) and got it to flash again after playing it for a few minutes.

Battery at 83%.
Surface temp approx 28C 82F

Interesting note when i can reproduce the bright white flash:
1) i unlock and then lock the screen again quickly, the white flash becomes more dim
2) repeat (1) and the flash stops altogether

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-paneldelay_20200602.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4754081/Sultan-kernel-wahoo-paneldelay_20200602.zip)

Try this kernel now.

**Comment by TomK** [comment]
Running that one now, i will get back to you asap. Thanks

**Comment by TomK** [comment]
@kerneltoast  I've been unable to get this version to break after following the usual steps both last night and this morning. Looks good to me 👍

**Comment by kerneltoast** [comment]
Looks like it was caused by a88bb7bd488d104785b9200d8abeae066acd2315, but that's a nice commit. Let's see if we can tweak it a bit and keep the fast display power on.

[Sultan-kernel-wahoo-intwidthdly_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4762061/Sultan-kernel-wahoo-intwidthdly_20200610.zip)

Try this kernel.

**Comment by TomK** [comment]
I'm afraid this one is intermittently flashing both on screen timeout and when a notification arrives.

**Comment by TomK** [comment]
do you have any idea what they mean by "low temperature"?  if i can ascertain a target temp it might make it simpler to test.  I couldn't see any specific information in the commit notes

**Comment by kerneltoast** [comment]
No idea what they mean by low temperature. I put my phone in the refrigerator for an hour and, even though it was quite cold, it didn't have any flashes.

[Sultan-kernel-wahoo-20msstepup_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766043/Sultan-kernel-wahoo-20msstepup_20200610.zip)

Try this kernel.

**Comment by TomK** [comment]
managed to get an approx 30% brightness flash just now with this 20ms.  It's liveable, but it depends on how far you want to go with this.

**Comment by kerneltoast** [comment]
Livable isn't good enough; there needs to be zero glitches.

[Sultan-kernel-wahoo-90msstepup_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766102/Sultan-kernel-wahoo-90msstepup_20200610.zip)

Try this kernel.

**Comment by TomK** [comment]
i'm glad you said that, patching now.

**Comment by TomK** [comment]
still getting it on 90ms. actually very similar to the 20ms one.

seems to be most consistent immediately after a reboot:
1) reboot
2) immediately open play store
3) use power button to turn off screen
   - flash happens pretty much mid-point between screen going dark and ambient display turning on

so:  power button pressed, screen goes dark, flash then dark again, ambient display on

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-sleepexit60ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766196/Sultan-kernel-wahoo-sleepexit60ms_20200610.zip)

Try this kernel.

**Comment by TomK** [comment]
ok, i've got this one to flash a few times, but not full brightness and not every time.  the above reproduction steps now only work half the time

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-fulldlynewclkpostpre_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766248/Sultan-kernel-wahoo-fulldlynewclkpostpre_20200610.zip)

Try this. It's almost the same as Sultan-kernel-wahoo-paneldelay_20200602.zip. If this is fine, I think I'm going to go ahead and revert the panel delay reduction after giving you one more test.

**Comment by TomK** [comment]
This looks good. Currently unable to reproduce

**Comment by TomK** [comment]
Feel free to send over some sanity checks 👍

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-60ms20ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766411/Sultan-kernel-wahoo-60ms20ms20ms_20200610.zip)

Try this. I'm going to try and see if your device can tolerate just slightly reducing some panel delays.

**Comment by TomK** [comment]
no flashing on power button -> ambient

but a very bright flash on notification. this one is much more awkward to test unless i write an app to send a notification after a specific time delay.  It happened by chance just now.

**Comment by TomK** [comment]
interestingly having just said that, i now got a very bright flash after pressing the power button.
I'm sorry this is possibly a hinderance rather than a help

**Comment by kerneltoast** [comment]
Not a problem. It either works or it doesn't. In this case it looks like it doesn't, so here's another test.

[Sultan-kernel-wahoo-60ms60ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766495/Sultan-kernel-wahoo-60ms60ms20ms_20200610.zip)

**Comment by TomK** [comment]
haven't been able to get this to flash.  either by power button, timeout, or notification.

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-60ms40ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766569/Sultan-kernel-wahoo-60ms40ms20ms_20200610.zip)

Oh cool there's some leeway. Try this.

**Comment by TomK** [comment]
this looks good too, in all cases 👍

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-60ms30ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766601/Sultan-kernel-wahoo-60ms30ms20ms_20200610.zip)

Cool, try this.

**Comment by TomK** [comment]
looks good so far, just waiting for a notification so i can test the wakeup too

**Comment by TomK** [comment]
just received some notifications, no flashing. looks good

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-30ms30ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766755/Sultan-kernel-wahoo-30ms30ms20ms_20200610.zip)

Nice, that's a 60ms savings we get to keep. Try this.

**Comment by TomK** [comment]
this looks good also :)

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-10ms30ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766821/Sultan-kernel-wahoo-10ms30ms20ms_20200610.zip)

Nice, try this.

**Comment by TomK** [comment]
unfortunately this version is flashing on a fresh boot with the power button

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms30ms20ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766920/Sultan-kernel-wahoo-20ms30ms20ms_20200610.zip)

How about this.

**Comment by TomK** [comment]
this is working for me 👍

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms30ms5ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766969/Sultan-kernel-wahoo-20ms30ms5ms_20200610.zip)

Awesome, try this.

**Comment by TomK** [comment]
This is also good for me

**Comment by kerneltoast** [comment]
Use that kernel for at least 2 days to see if any problems arise. If a flash occurs, you can immediately leave a comment here saying that it failed.

**Comment by kerneltoast** [comment]
Actually, let me give you one more kernel @TomK

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms30ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4767064/Sultan-kernel-wahoo-20ms30ms0ms_20200610.zip)

Use this kernel for 2-3 days, unless it shows problems immediately.

**Comment by TomK** [comment]
running with the latest 20/30/0 as it seems to be working atm

**Comment by TomK** [comment]
just had a few flashes on this version.  will rollback to 20/30/5 and run that for a while

**Comment by kerneltoast** [comment]
Did they occur when you got a notification, or when you turned the screen off with the power button? I don't think the 20/30/5 kernel will be any different; it seems like that final delay isn't necessary.

**Comment by TomK** [comment]
I can't be certain which triggered it. It's most likely that it was power button.
I pressed the power button, put the phone down and then saw a flash.  Although i did get a notification around the same time.

Since I rolled back to 20/30/5 i haven't experienced the issue again (yet)

**Comment by kerneltoast** [comment]
I suspect you'll have the same issue with 20/30/5, but let's wait and see anyway I guess.

**Comment by TomK** [comment]
Just got the same issue with 20/30/5, it was a display timeout.
I had it next to me with the screen on, it turned off after the timeout and flashed before the ambient display came on.

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-30ms30ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4773093/Sultan-kernel-wahoo-30ms30ms0ms_20200610.zip)

Alright, try this one.

**Comment by TomK** [comment]
Just had a flash on power button press

**Comment by TomK** [comment]
Just had another flash when turning the screen on this time. Took it out of my pocket, pressed the button and it flashed before the screen came on

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms40ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4775300/Sultan-kernel-wahoo-20ms40ms0ms_20200610.zip)

How about this

**Comment by TomK** [comment]
running this now, will keep you updated

**Comment by TomK** [comment]
Just had a flash on screen timeout

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-40ms30ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4777041/Sultan-kernel-wahoo-40ms30ms0ms_20200610.zip)

Hmm, maybe it's that first delay. Try this.

**Comment by TomK** [comment]
Just had a power button flash on this version

**Comment by TomK** [comment]
Just wanted to check. The version still shows date as 10th june in settings. Is that correct, or is twrp failing to flash properly?

```
4.4.210-Sultan
#1 Wed Jun 10 18:22:18 PDT 2020
```

**Comment by kerneltoast** [comment]
Yeah, that's correct. Only the dtbo is being changed.

**Comment by TomK** [comment]
ok, looks like this one is failing also i'm afraid, had it flash on power button earlier this morning.  Will continue to monitor it for now.

**Comment by kerneltoast** [comment]
Sorry I fell asleep and didn't give you another test. I'll send another in a bit.

**Comment by kerneltoast** [comment]
Use the 20/30/20 kernel from a previous comment: https://github.com/kerneltoast/android_kernel_google_wahoo/files/4766920/Sultan-kernel-wahoo-20ms30ms20ms_20200610.zip

**Comment by TomK** [comment]
Just had quite a few flashes on this one. Notification and also power button.

Plugged in, at 100% charge

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms90ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4787637/Sultan-kernel-wahoo-20ms90ms0ms_20200610.zip)

Hmm, let's try isolating which delay is at fault. Try this.

**Comment by TomK** [comment]
I've been running this since you posted it, no issues so far.

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms50ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4795983/Sultan-kernel-wahoo-20ms50ms0ms_20200610.zip)

Cool, we're getting close.

**Comment by TomK** [comment]
Running this now 👍

**Comment by TomK** [comment]
just failed on power button press

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms60ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4799321/Sultan-kernel-wahoo-20ms60ms0ms_20200610.zip)

Only a few more to go.

**Comment by TomK** [comment]
same again on this one. flash on power button press

**Comment by kerneltoast** [comment]
[Sultan-kernel-wahoo-20ms70ms0ms_20200610.zip](https://github.com/kerneltoast/android_kernel_google_wahoo/files/4800540/Sultan-kernel-wahoo-20ms70ms0ms_20200610.zip)

Wow, we might not be able to reduce that middle delay at all. Here's another.

**Comment by TomK** [comment]
Got another flash I'm afraid

**Comment by kerneltoast** [comment]
Wow, okay! Keep using the 20/90/0 kernel for a bit longer (https://github.com/kerneltoast/android_kernel_google_wahoo/files/4787637/Sultan-kernel-wahoo-20ms90ms0ms_20200610.zip) and if all is well, that's what I'll push. I don't think we can shave off anything from the 90ms delay.

**Comment by TomK** [comment]
Righto, reverting to that now 👍

**Comment by TomK** [comment]
So far so good, been running it for 4 days with regular usage.

**Comment by kerneltoast** [comment]
Cool, I'll roll with that then. Make a new issue for DFS and I'll take a look either this weekend or next week. I'm moving so this week is going to be busy for me...

**Comment by TomK** [comment]
No madness, I really appreciate the time you put into this!
